language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: QnBlAkZGmP3qwaHbnjvH0RQXCD/XJsJN/QA+UQNIyM34chiICedVriETGCw47gVB5SJ5nXqH+WTIhfFfiNOErlLqhI/EfUdCMH95rn4aezy8JzUo257awYON74Fs2zOBr1LJkMUZq0xm7dUERHzfHebXg1MMfcxmvMe18HAuRHw=
  - secure: O5YJ9SB6iEhcobQpUdb6kolBnbuwdUPp5V7ou6nC/ZFz3Klmeq4FtpG0U2prxVF8RQ4O2+jPHWToGjXPZF+9A4HNZ8L/+v7xZQzqEh48RFt8Cbs2H9aoevH5hvovtsJCQac7ZVs/z4VfS6PZ47za2rEKWK+S33QTTFioI8W4clo=
  - secure: Nilli5/iwPLDcbnT3w1SNpWRil3BJCgX4MtK7vodZdNujwCvxUeKYJ19qfDVGDEPg7ghEoJ1yfGDq9lGTNlvWgr5G2CrKp7KnKqHIjwxbW5me/vRMGkzzTfuKgzH7zxmZwqSZZyqWaDKaYKhZ+B5vCxFuc7CWypziIrHiOb02Y4=
  - secure: eFrUy3YAnjzcBx0mKi6/qTmyQuYV5a9fzTVGsvwYM0x0+y4e3+Z1G4yEkj5gSgla6TSoGHvXSt3w8S43qJYj9TcRm1dK/KjJcr3kqXJwqdijTzSfiEuKRUlfTGUfYTjxlq5LQaRS5WOzPoCwNrPKhvkbBwaHCedrXG5+eeErlFY=
